rule: //div[@class='product_card']
repeat: true
ignoretext: true
configs:
  - rule: .//a[@class='name']
    istitle: true
  - rule: .//div[@class='image']/a/@href
  - rule: .//div[@class='grey-block']/p[@class='price']