rule: //div[@class='product_card']
repeat: true
ignoretext: true
nextpage: //div[@class='pagination']/div[@class='links']/b/following-sibling::a/@href
configs:
  - rule: .//a[@class='name']
    istitle: true
  - rule: .//div[@class='image']/a/@href
  - rule: .//div[@class='grey-block']/p[@class='price']