rule: //div[@class='product_card']
repeat: true
usetext: false
configs:
  - rule: .//div[@class='image']/a/@href
    usetext: true
  - rule: .//div[@class='grey-block']/p[@class='price']
    usetext: true
  - rule: .//div[@class='name']